# Generated by Django 5.0.1 on 2024-01-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(null=True)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'NON-IT'), ('TRANSPORT', 'TRANSPORT')], max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
